# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#     ┏━━━┓━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┏┓━┏┓━┏┓━━━┏┓━━━━━      #
#     ┃┏━┓┃━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┃┃━┃┃┏┛┗┓━━┃┃━━━━━      #
#     ┃┃━┗┛┏━━┓━┏━┓━┏━┓━┏━━┓┏━┓━┏┓┏━┓━┏━━┓┃┃━┃┃┗┓┏┛┏┓┃┃━┏━━┓      #
#     ┃┃━┏┓┗━┓┃━┃┏┓┓┃┏┓┓┃┏┓┃┃┏┓┓┣┫┃┏┓┓┃┏┓┃┃┃━┃┃━┃┃━┣┫┃┃━┃━━┫      #
#     ┃┗━┛┃┃┗┛┗┓┃┃┃┃┃┃┃┃┃┗┛┃┃┃┃┃┃┃┃┃┃┃┃┗┛┃┃┗━┛┃━┃┗┓┃┃┃┗┓┣━━┃      #
#     ┗━━━┛┗━━━┛┗┛┗┛┗┛┗┛┗━━┛┗┛┗┛┗┛┗┛┗┛┗━┓┃┗━━━┛━┗━┛┗┛┗━┛┗━━┛      #
#     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┏━┛┃━━━━━━━━━━━━━━━━━━      #
#     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┗━━┛━━━━━━━━━━━━━━━━━━      #
#     By: __flaming, chronny1549                                  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #